apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: $TOKEN
    apiServerEndpoint: "172.31.85.216:6443"
    caCertHashes:
      - $CACERT_HASH
nodeRegistration:
  name: ip-172-31-85-30.ec2.internal
  kubeletExtraArgs:
    cloud-provider: aws
controlPlane:
  localAPIEndpoint:
    advertiseAddress: 172.31.85.30
  certificateKey: $CERT_KEY
